import { SidebarItemProps } from '@/components/Sidebar/Sidebar.interface'

export const ABOUT_LINKS: Array<SidebarItemProps> = [
  { id: 1, label: 'Office of Head of Service', link: '/about' },
  { id: 2, label: 'Mission and Vision', link: '/about/mission-and-vision' },
  { id: 3, label: 'Past Heads of Service', link: '/about/past-hos' },
]

export const MDAs = [
  {
    id: 1,
    title: 'Ministry of Agriculture and Rural Development',
    dept: 3,
    agencies: 3,
    img: 'agric.jpg',
  },
  {
    id: 2,
    title: 'Ministry of Environment and Forestry Resources',
    dept: 3,
    agencies: 3,
    img: 'enviro.png',
  },
  {
    id: 3,
    title: 'Ministry of Livestock and Fisheries',
    dept: 3,
    agencies: 3,
    img: 'livestock.jpg',
  },
  {
    id: 4,
    title: 'Ministry of Investment, Commerce and Co—operatives',
    dept: 3,
    agencies: 3,
    img: 'office.jpg',
  },
  {
    id: 5,
    title: 'Ministry of Tourism and Culture',
    dept: 3,
    agencies: 3,
    img: 'tour.jpg',
  },
  {
    id: 6,
    title: 'Ministry of Education',
    dept: 3,
    agencies: 3,
    img: 'edu.jpg',
  },
  {
    id: 7,
    title: 'Ministry of Finance',
    dept: 3,
    agencies: 3,
    img: 'finance.jpg',
  },
  {
    id: 8,
    title: 'Ministry of Health',
    dept: 3,
    agencies: 3,
    img: 'health.jpg',
  },
  {
    id: 9,
    title: 'Ministry of Information and Communications',
    dept: 3,
    agencies: 3,
    img: 'info.png',
  },
  {
    id: 10,
    title: "Attorney General's Chamber and Ministry of Justice",
    dept: 3,
    agencies: 3,
    img: 'justice.jpg',
  },
  {
    id: 11,
    title: 'Ministry of Gender Affairs and Social Development',
    dept: 3,
    agencies: 3,
    img: 'gender.png',
  },
  {
    id: 12,
    title: 'Ministry of Local Government, (Community Development and Chieftaincy Affairs)',
    dept: 3,
    agencies: 3,
    img: 'lga.jpg',
  },
  {
    id: 13,
    title: 'Ministry of Water Resources',
    dept: 3,
    agencies: 3,
    img: 'water.jpg',
  },
  {
    id: 14,
    title: 'Ministry of Transport',
    dept: 3,
    agencies: 3,
    img: 'transport.jpg',
  },
  {
    id: 15,
    title: 'Ministry of Works and Infrastructural Development',
    dept: 3,
    agencies: 3,
    img: 'works.jpg',
  },
  {
    id: 16,
    title: 'Ministry of Lands and Housing',
    dept: 3,
    agencies: 3,
    img: 'land.jpg',
  },
  {
    id: 17,
    title: 'Ministry of Tertiary Education',
    dept: 3,
    agencies: 3,
    img: 'tert.jpg',
  },
  {
    id: 18,
    title: 'Ministry of Science and Technology',
    dept: 3,
    agencies: 3,
    img: 'sci.jpg',
  },
  {
    id: 19,
    title: 'Ministry of Religious Affairs and Poverty Eradication',
    dept: 3,
    agencies: 3,
    img: 'rel.jpg',
  },
  {
    id: 20,
    title: 'Ministry of Youths Development',
    dept: 3,
    agencies: 3,
    img: 'youths.jpg',
  },
  {
    id: 21,
    title: 'Ministry of Sports Development',
    dept: 3,
    agencies: 3,
    img: 'sports.jpg',
  },
  {
    id: 22,
    title: 'Ministry of Mining and Solid Mineral Resources',
    dept: 3,
    agencies: 3,
    img: 'mining.jpg',
  },
]

export const PAST_HOS = [
  {
    id: 1,
    imgName: 'pastHOS/1.jpg',
    name: 'Alhaji Abdulkarim Lafene',
    dob: 'February, 1929',
    lga: 'Rafi Local Government',
    designation: 'Secretary to the Military Government (SMG)',
    period: '1976',
  },
  {
    id: 2,
    imgName: 'pastHOS/2.jpg',
    name: 'Alhaji Suleiman Liman',
    dob: '3rd January, 1935',
    lga: 'Agaie Local Government',
    designation: 'Secretary to the Military Government (SMG)',
    period: '1976 - 1979',
  },
  {
    id: 3,
    imgName: 'pastHOS/3.jpg',
    name: 'Amb. J. T. Kolo',
    dob: '31st July, 1938',
    lga: 'Lavun Local Government',
    designation: 'Head of Service',
    period: '1976 - 1983',
  },
  {
    id: 4,
    imgName: 'pastHOS/4.jpg',
    name: 'Alhaji Shehu Ahmadu Katcha',
    dob: '1st April, 1972',
    lga: 'Katcha Local Government',
    designation: 'Head of Service',
    period: '1983 - 1983',
  },
  {
    id: 5,
    imgName: 'pastHOS/5.jpg',
    name: 'Amb. Abdulrahman Gara',
    dob: '15th May, 1940',
    lga: 'Lapai Local Government',
    designation: 'Head of Service',
    period: '1983 - 1986',
  },
  {
    id: 6,
    imgName: 'pastHOS/6.jpg',
    name: 'Engr. M. Muhammad, mni',
    dob: '8th October, 1945',
    lga: 'Bida Local Government',
    designation: 'Secretary to the Military Government, Head of Service',
    period: '1987 - 1992',
  },
  {
    id: 7,
    imgName: 'pastHOS/7.jpg',
    name: 'Nuhu Galadima',
    dob: '',
    lga: 'Shiroro Local Government',
    designation: 'Secretary to the State Government',
    period: '1992 - 1994',
  },
  {
    id: 8,
    imgName: 'pastHOS/8.jpg',
    name: 'Alh. Abdulkadir Gudugi',
    dob: '15th June, 1953',
    lga: 'Wushishi Local Government',
    designation: 'Secretary to the State Government',
    period: '1994 - 1998',
  },
  {
    id: 9,
    imgName: 'pastHOS/9.jpg',
    name: 'Alh. Nuhu Bawa',
    dob: '21st January, 1946',
    lga: 'Wushishi Local Government',
    designation: 'Head of Service',
    period: '1999 - 2002',
  },
  {
    id: 10,
    imgName: 'pastHOS/10.jpg',
    name: 'Alh Hassan Yahaya',
    dob: '',
    lga: 'Kontagora Local Government',
    designation: 'Head of Service',
    period: '2002 - 2004',
  },
  {
    id: 11,
    imgName: 'pastHOS/11.jpg',
    name: 'Alh. Abdulkadir Usman',
    dob: '25th December, 1947',
    lga: 'Wushishi Local Government',
    designation: 'Head of Service',
    period: '2004 - 2007',
  },
  {
    id: 12,
    imgName: 'pastHOS/12.jpg',
    name: 'Alh. Abdullahi Umar Danyaya',
    dob: '2nd May, 1952',
    lga: 'Kontagora Local Government',
    designation: 'Head of Service',
    period: '2007 - 2010',
  },
  {
    id: 13,
    imgName: 'pastHOS/13.jpg',
    name: 'Ahmed Ibrahim Matane',
    dob: '27th December, 1962',
    lga: 'Mashegu Local Government',
    designation: 'Head of Service',
    period: '2010 - 2013',
  },
  {
    id: 14,
    imgName: 'pastHOS/14.jpg',
    name: 'Barr. Abbas Bello',
    dob: '24th November, 1956',
    lga: 'Paikoro Local Government',
    designation: 'Head of Service',
    period: '2013 - 2014',
  },
  {
    id: 15,
    imgName: 'pastHOS/15.jpg',
    name: 'Hamidu A. A. Kadi-Kuta, mni',
    dob: '1st January, 1959',
    lga: 'Shiroro Local Government',
    designation: 'Head of Service',
    period: '2014 - 2015',
  },
  {
    id: 16,
    imgName: 'pastHOS/16.jpg',
    name: 'Mohammed Maude Lapai, mni',
    dob: '30th November, 1956',
    lga: 'Lapai Local Government',
    designation: 'Head of Service',
    period: '2015 - 2016',
  },
  {
    id: 17,
    imgName: 'pastHOS/17.jpg',
    name: 'Yabagi Alhaji Sule',
    dob: '15th January, 1959',
    lga: 'Bida Local Government',
    designation: 'Head of Service',
    period: '2016 - 2019',
  },
  {
    id: 18,
    imgName: 'pastHOS/18.jpg',
    name: 'Haj. Salamatu T. Abubakar',
    dob: '20th March, 1964',
    lga: 'Agaie Local Government',
    designation: 'Head of Service',
    period: '2019 - Present',
  },
]

export const StateLogo = '/images/state-logo.png'
